FROM golang:1.25.1

RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /app

COPY . .

EXPOSE 8080 2345

# Прямой запуск без предварительной сборки
CMD ["dlv", "debug", "./cmd/main.go", "--headless", "--listen=:2345", "--api-version=2", "--accept-multiclient", "--output=/tmp/debug_binary", "--log", "--"]